'use client';
import { Container, Typography, createTheme, ThemeProvider } from "@mui/material";
import { Metadata } from "next";
import { Roboto } from "next/font/google";
import Image from "next/image";

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Filipizen - Error",
  description: "Generated by create next app",
}

export let fontTheme = createTheme({
  typography: {
    fontFamily: roboto.style.fontFamily,
  }
})

const Custom404 = ({partnerName}: any) => {
  return (
    <ThemeProvider theme={fontTheme}>
      <Container 
        className='my-[16px] static text-slate-800'
        maxWidth='sm'
        disableGutters
      >
        <Image 
          src={"/assets/filipizen.svg"} 
          alt={"Filipizen Logo"} 
          width={220}
          height={60.66}
          className="pt-[32px]"
        />
        <Typography
          variant="h1"
          className="mt-[32px] mb-[16px] text-[32px] font-bold"
        >
          Partner {partnerName} is currently inactive.
        </Typography>
        <Typography
          className="my-[17.4px] text-[14.8px] text-[#000000a6] leading-snug opacity-70"
          style={{
            display: 'block',
            marginBlockStart: '1em',
            marginBlockEnd: '1em',
            marginInlineStart: '0px',
            marginInlineEnd: '0px',
          }}
        >
          Kindly verify that the partner name is correct and try again.
        </Typography>
      </Container>
    </ThemeProvider>
  );
};

export default Custom404;
