import React from "react";
import { Metadata } from "next"; 

export const metadata: Metadata = {
  title: "Filipizen - Inactive",
  description: "Generated by create next app",
}

const InactiveLayout = async ({ children }: { children: React.ReactNode }) => {  
  return (
    <main>
      {children}
    </main>
  );
}

export default InactiveLayout;
