// import { Metadata } from 'next';
// import { getMembersData } from '@/app/utils/helpers';
// import { connectMongoDB } from '@/lib/mongodb';
// import { getServerSession } from 'next-auth';
// import User from '@/models/user';
// import { redirect } from 'next/navigation';
// import Custom404 from '@/app/components/layout/Custom404';

// export const metadata: Metadata = {
//   title: 'Filipizen - Partners',
//   description: 'Filipizen Website',
// }

// interface PageProps {
//   params: {partnerLink: string};
// }

// interface Member {
//   id: number;
//   clusterid: string;
//   title: string;
//   subtype: string;
//   state: string;
//   email: string;
//   name: string;
//   includeservices: string;
//   excludeservices: string;
//   phoneno: string;
//   group: {
//     name: string;
//     objid: string;
//     title: string;
//   } 
//   channelid: string;
//   isonline: string;
// }

// const page:React.FC<PageProps> = async({params}) => {
//   const partnerData: Member[] = await getMembersData();
//   const acceptedUrlParams: string[] = [];

//   await connectMongoDB();
//   const session = await getServerSession();
//   const email = session?.user?.email;
//   const user = await User.findOne({ email });

//   if (user && user.isFirstTimeSigningIn) {
//     redirect('/');
//   }

//   partnerData.map((partner) => {
//     acceptedUrlParams.push(partner.group.name + "_" + partner.name);
//   })

//   if (acceptedUrlParams.includes(params.partnerLink)) {
//     redirect(params.partnerLink+"/services")
//   }

//   else {
//     return <Custom404 />
//   }
// }

// export default page
import Custom404 from '@/app/components/layout/Custom404'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Filipizen - Error",
  description: "Generated by create next app",
}

const page = () => {
  return (
    <Custom404 />
  )
}

export default page

