import { Metadata } from "next";
import Footer from "@/components/ui/Footer";
import { Raleway, Roboto } from "next/font/google";
import { getMembersData } from "../services/CloudPartnerService";
import LandingPage from "./LandingPage";
import Panel from "@/components/io/Panel";

export const metadata: Metadata = {
  title: "Welcome - Filipizen",
  description: "Generated by create next app",
}

const raleway = Raleway({ 
  weight: ["400", '500', '700'], 
  subsets: ["latin"],  
  display: 'swap'
});

export default async function Home() {
  const memberData = await getMembersData();
  
  return (
    <main className={`relative flex min-h-screen flex-col items-center justify-between ${raleway.className}`}>
      <LandingPage memberData={memberData}/>
      <Panel className="absolute bottom-0 w-full">
        <Footer />
      </Panel>
    </main>
    
  );
}