'use client';
import { Container, Typography, createTheme, ThemeProvider } from "@mui/material";
import { Metadata } from "next";
import { Roboto } from "next/font/google";
import Image from "next/image";
import { headers } from 'next/headers'
import Link from "next/link";

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Filipizen - Error",
  description: "Generated by create next app",
}

export let fontTheme = createTheme({
  typography: {
    fontFamily: roboto.style.fontFamily,
  }
})

const NotAvailable = () => {
  return (
    <ThemeProvider theme={fontTheme}>
      <Container 
        className='my-[16px] static text-slate-800'
        maxWidth='sm'
        disableGutters
      >
        <Link href='/'>
          <Image 
            src={"/assets/filipizen.svg"} 
            alt={"Filipizen Logo"} 
            width={220}
            height={60.66}
            className="pt-[32px]"
          />
        </Link>
        
        <Typography
          variant="h1"
          className="mt-[32px] mb-[16px] text-[28px] font-bold"
        >
          Not Available
        </Typography>
        {/* <Typography
          className="mb-[16px] text-[#000000a6] leading-none font-bold"
        >
          404 - PAGE NOT FOUND
        </Typography> */}
        <Typography
          className="my-[17.4px] text-[14.8px] text-[#000000a6] leading-snug opacity-70"
          style={{
            display: 'block',
            marginBlockStart: '1em',
            marginBlockEnd: '1em',
            marginInlineStart: '0px',
            marginInlineEnd: '0px',
          }}
        >
          This page is not yet available.
        </Typography>
      </Container>
    </ThemeProvider>
  );
};

export default NotAvailable;
