import { Metadata } from "next"
import SignInPage from "../components/layout/SignInPage"

export const metadata: Metadata = {
    title: "Sign In - Filipizen",
    description: "Generated by create next app",
  }

const page = async() => {
//   const res = await fetch("https://filipizen.com/cloud-server/json/partner/CloudPartnerService.getList", {
//     next: { revalidate: 3600 },
//   });

//   if(!res.ok) {
//     throw new Error('Error fetching data');
//   }

//   const data = await res.json;

//   console.log(data);
  return <SignInPage />
}

export default page;