import { Metadata } from "next"
import SignInPage from "../components/layout/SignInPage"

export const metadata: Metadata = {
    title: "Sign In - Filipizen",
    description: "Generated by create next app",
  }

const page = async() => {
  return <SignInPage />
}

export default page;