version: "3"

services:
  
   filipizen-main:
      container_name: filipizen-main
      image: ramesesinc/filipizen-main:1.01
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: 10m
      ports:
         - "4001:3000"
