import { Metadata } from "next"
import SetUpProfilePage from "../components/layout/SetUpProfilePage"
import { connectMongoDB } from '@/lib/mongodb';
import User from '@/models/user';
import { redirect } from 'next/navigation';
import { getServerSession } from "next-auth/next"


export const metadata: Metadata = {
  title: "First Time Sign In - Filipizen",
  description: "Generated by create next app",
}
const page = async() => {
  await connectMongoDB();
  const session = await getServerSession();
  const email = session?.user?.email;
  const user = await User.findOne({ email });

  if (user && !user.isFirstTimeSigningIn) {
    redirect('/signinchecker');
  }

  else if(!user) {
    redirect('/signinchecker');
  }
  
  else {
    return <SetUpProfilePage />
  }
}

export default page