import { Metadata } from "next"
import SetUpProfilePage from "../components/layout/SetUpProfilePage"
import { connectMongoDB } from '@/lib/mongodb';
import User from '@/models/user';
import { redirect } from 'next/navigation';
import { getServerSession } from "next-auth/next"
import { Suspense } from "react";
import Loading from "./loading";
import ContentWrapper from "../components/ui/ContentWrapper";

export const metadata: Metadata = {
  title: "First Time Sign In - Filipizen",
  description: "Generated by create next app",
}

const page = async() => {
  await connectMongoDB();
  const session = await getServerSession();
  const email: any = session?.user?.email;
  const name: any = session?.user?.name;
  const user = await User.findOne({ email });

  console.log(session);

  if (user && !user.isFirstTimeSigningIn) {
    redirect('/signinchecker');
  }

  else if(!user) {
    redirect('/signinchecker');
  }
  
  else {
    return (
      <ContentWrapper className="h-screen w-screen">
        <Suspense fallback={<Loading />}>
          <SetUpProfilePage 
            userEmail={email}
            name={name}
          />
        </Suspense>
      </ContentWrapper>
    )
  }
}

export default page