import { Metadata } from "next"
import SignUpPage from "../components/layout/SignUpPage"

export const metadata: Metadata = {
    title: "Sign Up - Filipizen",
    description: "Generated by create next app",
  }

const page = async() => {

  return <SignUpPage />
}

export default page;